/*
 * ULTRASONIC.c
 *
 *  Created on: Oct 18, 2023
 *      Author: Yassin
 *      Description: ULTRASONIC source file
 */

#include "../MCAL/icu.h"
#include "../std_types.h"
#include "LCD.h"
#include "ULTRASONIC.h"
#include <util/delay.h>

static uint8 g_edgeCount = 0;
static uint16 g_timeHigh = 0;
static uint8 g_obsDistance = 0;


/*****************************************************
 * Both functions are static to limit their scope
 *  to file scope
 *****************************************************/
static void Ultrasonic_edgeProcessing(void);
static void Ultrasonic_Trigger(void);

/*
 * Initialize the ICU driver
 * Pre-scaler = 8
 * Capture on rising edge
 * setting the callback function in icu driver to Ultrasonic_edgeProcessing
 * Setup the direction for the trigger pin as output pin through the GPIO driver
 */
void Ultrasonic_init(void)
{
	ICU_ConfigType icu1;
	icu1.clockSelect = F_CPU_8;
	icu1.edgeSelect = RISING;
	ICU_init(&icu1);
	ICU_setCallBack(Ultrasonic_edgeProcessing);
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, PIN_OUTPUT);


}

/*
 * Description
 * Function is static to limit its scope to this file only
 * Trigger the ultrasonic trigger pin
 * to trigger frequency generated by the sensor
 */
static void Ultrasonic_Trigger(void)
{
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, LOGIC_LOW);
}

/*
 *
 */
uint16 Ultrasonic_readDistance(void)
{
	g_obsDistance = 0;
	g_edgeCount = 0;
	g_timeHigh = 0;

	ICU_clearTimerValue();
	Ultrasonic_Trigger();


	while(g_edgeCount != 2);
	g_obsDistance = g_timeHigh / 58;

	return g_obsDistance+1;
}
static void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		ICU_clearTimerValue();
		ICU_setEdgeSelect(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		g_timeHigh = ICU_getICRValue();
		ICU_setEdgeSelect(RISING);
	}

}
